apiVersion: v1
kind: Service
metadata:
  name: resource-consumer-constant
spec:
  selector:
    app: resource-consumer-constant
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: resource-consumer-constant
  labels:
    name: resource-consumer-constant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resource-consumer-constant
  template:
    metadata:
      labels:
        app: resource-consumer-constant
    spec:
      containers:
        - name: resource-consumer-constant
          image: gcr.io/k8s-staging-e2e-test-images/resource-consumer:1.9
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 150m
              memory: 128Mi
            limits:
              memory: 256Mi
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: curl-resource-consumer-constant
spec:
  schedule: "0 0 * * *"
  concurrencyPolicy: Replace
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: curl-cpu
            image: curlimages/curl
            imagePullPolicy: IfNotPresent
            args:
              - -d
              - "millicores=150&durationSec=43200"
              - http://resource-consumer-constant:8080/ConsumeCPU
          - name: curl-mem
            image: curlimages/curl
            imagePullPolicy: IfNotPresent
            args:
              - -d
              - "megabytes=128&durationSec=43200"
              - http://resource-consumer-constant:8080/ConsumeMem
          restartPolicy: OnFailure
