apiVersion: apps/v1
kind: Deployment
metadata:
  name: costestimation
  labels:
    name: costestimation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: costestimation
  template:
    metadata:
      labels:
        app: costestimation
    spec:
      containers:
        - name: costestimation
          image: jessicabarai/dat067-costestimation:latest
          command: ["costestimation"]
          args: ["-url", "http://prometheus-server"] 
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 150m
              memory: 128Mi
